[tool.poetry]
name = "tic-tac-toe"
version = "0.1.0"
description = ""
authors = ["Filippo Pracucci <filippo.pracucci@studio.unibo.it>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pygame = "^2.6.0"
pygame-menu = "^4.5.2"

[tool.poetry.scripts]
local = "tic_tac_toe:main"
lobby-coordinator = "tic_tac_toe.remote.centralised:main_lobby"
terminal = "tic_tac_toe.remote.centralised.terminal:main_terminal"
test = "tests.runner:run_tests"
test-model = "tests.runner:run_model_tests"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"
